development:
  adapter: redis
  url: <%= ENV['REDIS_URL'] || 'redis://localhost:6379/1' %>

test:
  adapter: async

staging:
  adapter: redis
  url: <%= ENV['REDIS_URL'] || 'redis://localhost:6379/1' %>

production:
  adapter: redis
  url: <%= ENV['REDIS_URL'] || 'redis://localhost:6379/1' %>
